mysql:
  image: mysql:5.7
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=petclinic
    - MYSQL_DATABASE=petclinic
  volumes:
    - "./conf.d:/etc/mysql/conf.d:ro"
mysql:
  image: mysql:5.7
  ports:
    - "80:80"
  environment:
    - PMA_HOST=mysql
    - PMA_PORT=3306
    - MYSQL_ROOT_PASSWORD=petclinic
  volumes:
    - "./conf.d:/etc/mysql/conf.d:ro"
